### ISSUE TITLE
Doesn't make dirt if detonated and falls onto a slab

### ISSUE THREAD

**Issue by Buggitt** [Fourmisain/DirTNT#2]
![image](https://user-images.githubusercontent.com/7709438/128166206-b252d9a4-6dfd-45dd-ab0c-d22463602bd3.png)
If I flick the lever it'll ignite but not place dirt

Not sure what the intended result is, but in case it's not.

**Comment by Buggitt** [comment]
this also happens on carpet and I'd suspect any other not solid block

**Comment by Fourmisain** [comment]
Ah... looks like I need to improve the raytracing, that could take a bit to get right - again.

I think the issue is that `BlockView.raycast()` actually only goes by block _outline_ instead of collision shape, so a carpet is the same as a full block and the algo I wrote stops when hitting a solid block (so that dirt doesn't go through walls).

Thanks for the report! I'll see what I can do about this.

**Comment by Fourmisain** [comment]
Should be all fixed now, new version is released and approved!
