### ISSUE TITLE
Dispensers don't dispense dirtnt like tnt

### ISSUE THREAD

**Issue by Buggitt** [Fourmisain/DirTNT#3]

**Comment by Fourmisain** [comment]
I intentionally left that out because I didn't think anyone would wanna use that feature anytime soon - guess I was wrong 😄

This is now implemented in https://github.com/Fourmisain/DirTNT/commit/6ec2822ca1fc2a6d95d07975af46e7f2e772a19c for 1.17, merged into 1.16 as https://github.com/Fourmisain/DirTNT/commit/e5f6679c799152096f91d50dbb173e379e23327e.

Adding the dispensing logic was actually really easy but fixing 'dispensed' Flint and Steel on Dirt TNT was a lot more effort (mainly because IntelliJ would show me the wrong bytecode).
