### ISSUE TITLE
This mod can without Better Runtime Resource Pack (BRRP) if you have Enhanced Block Entities installed

### ISSUE THREAD

**Issue by Nukiloco** [Fourmisain/DirTNT#4]
What the title says. Sort of confusing?

**Comment by Fourmisain** [comment]
I just checked, this is because Enhanced Block Entities bundles ARRP.
DirTNT works with either ARRP or BRRP, one just has to make sure to not use both at once, so if you're using Enhanced Block Entities, you shouldn't install BRRP.
(ARRP and BRRP not working together is also the reason why I didn't bundle either of them in this mod.)
I hope this answers the question.
